version: '3'
services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade
    ports:
      - "8080:8080"
    volumes:
      - ../../../../../Documents/Freqtrade/user_data:/freqtrade/user_data

  freqtrade-experimental:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade-experimental
    ports:
      - "8081:8081"
    volumes:
      - ../../../../../Documents/Freqtrade/user_data:/freqtrade/user_data
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade-experimental.log
      --db-url sqlite:////freqtrade/user_data/freqtrade-experimental.sqlite
      --config /freqtrade/user_data/config_experimental.json
      --strategy SniperStrategy

  freqtrade-freqai:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade-freqai
    ports:
      - "8082:8082"
    volumes:
      - ../../../../../Documents/Freqtrade/user_data:/freqtrade/user_data
    environment:
      - FREQTRADE__FREQAI__ENABLED=true
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade-freqai.log
      --db-url sqlite:////freqtrade/user_data/freqtrade-freqai.sqlite
      --config /freqtrade/user_data/config_freqai.json
      --strategy FreqAIStrategy

    # command: >
    #   trade
    #   --logfile /freqtrade/user_data/logs/freqtrade.log
    #   --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
    #   --config /freqtrade/user_data/config.json
    #   --strategy SimpleStrategy
